version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432

  web:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - BUNDLE_APP_CONFIG=/app/.bundle
    volumes:
      - .:/app
      - bundle_path:/bundle/vendor
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  postgres:
  bundle_path:
